on:
  push:
    branches:
      - master

name: Build and Release new apk

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Getting the dependencies
        run: flutter pub get

      - name: Download keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | openssl base64 -d > android/app/key.jks

      - name: Create key.properties file
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Build the apk
        run: flutter build apk --dart-define TAG=v2.0.${{ github.run_number }} --dart-define GITHUB_TOKEN=${{ secrets.TOKEN }} --dart-define JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          tag: v2.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
